name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yordo81/tienda_mb:$(date +%s)
    - name: push image to docker hub
      run: docker push yordo81/tienda_mb:$(date +%s)
